# Generated by Django 4.2.3 on 2023-07-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_order_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_europ',
            name='contry',
            field=models.CharField(choices=[('France', 'France'), ('Italie', 'Italie'), ('Belgique', 'Belgique'), ('Allemagne', 'Allemagne'), ('Holanda', 'Holanda'), ('Engletere', 'Engletere')], max_length=20, null=True),
        ),
    ]
