# Generated by Django 4.2.3 on 2023-07-19 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_person_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='order_europ',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
