# Generated by Django 4.2.3 on 2023-07-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_order_published_date_order_europ_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
