# Generated by Django 4.2.3 on 2023-07-24 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_person_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='cni',
            new_name='ICE',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='nickname',
            new_name='company',
        ),
        migrations.RemoveField(
            model_name='person',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='person',
            name='gender',
        ),
        migrations.AddField(
            model_name='person',
            name='encadrement',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
