# Generated by Django 4.2.3 on 2023-07-31 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_rename_cni_person_ice_rename_nickname_person_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='ICE',
            field=models.CharField(default='CSTM', max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='company',
            field=models.CharField(default='CSTM', max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(default='CSTM', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='encadrement',
            field=models.CharField(default='CSTM', max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(default='CSTM', max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=models.CharField(default='CSTM', max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='prenom',
            field=models.CharField(default='CSTM', max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='weight',
            field=models.CharField(choices=[('3.5t-bache', '3.5t Bachè'), ('3.5t-plateau', '3.5t Plateau'), ('3.5t-plateau-ridal', '3.5t Plateau Ridal'), ('3.5t-avec-grue', '3.5t Avec Grue'), ('3.5t-fourgon', '3.5t Fourgon'), ('7.5t-bache', '7.5t Bachè'), ('7.5t-plateau', '7.5t Plateau'), ('7.5t-plateau-ridal', '7.5t Plateau Ridal'), ('7.5t-avec-grue', '7.5t Avec Grue'), ('7.5t-fourgon', '7.5t Fourgon'), ('10t-bache', '10t Bachè'), ('10t-plateau', '10t Plateau'), ('10t-plateau-ridal', '10t Plateau Ridal'), ('10t-avec-grue', '10t Avec Grue'), ('10t-fourgon', '10t Fourgon'), ('14t-bache', '14t Bachè'), ('14t-plateau', '14t Plateau'), ('14t-plateau-ridal', '14t Plateau Ridal'), ('14t-avec-grue', '14t Avec Grue'), ('14t-fourgon', '14t Fourgon'), ('19t-bache', '19t Bachè'), ('19t-plateau', '19t Plateau'), ('19t-plateau-ridal', '19t Plateau Ridal'), ('19t-avec-grue', '19t Avec Grue'), ('19t-fourgon', '19t Fourgon')], default='CSTM', max_length=20),
        ),
    ]
