# Generated by Django 4.2.3 on 2023-07-31 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_person_ice_alter_person_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='type_colis',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='order_europ',
            name='type_colis',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
