# Generated by Django 4.2.3 on 2023-08-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_order_type_colis_alter_order_europ_type_colis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_europ',
            name='contry',
            field=models.CharField(choices=[('France', 'France'), ('Italie', 'Italie'), ('Belgique', 'Belgique'), ('Allemagne', 'Allemagne'), ('Holanda', 'Holanda'), ('Engletere', 'Engletere')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order_europ',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order_europ',
            name='phone_number',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
