# Generated by Django 4.2.3 on 2023-08-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_carte_nom_carte_prenom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carte',
            name='nom',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='carte',
            name='prenom',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='ICE',
            field=models.CharField(default='CSTM', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(default='CSTM', max_length=254),
        ),
    ]
