# Generated by Django 4.2.3 on 2023-08-05 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_alter_carte_formation_carte_alter_carte_type_carte'),
    ]

    operations = [
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('link', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
