# Generated by Django 4.2.3 on 2023-08-15 08:45

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='link',
            field=embed_video.fields.EmbedVideoField(null=True),
        ),
    ]
