# Generated by Django 4.2.3 on 2023-08-15 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_alter_video_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='carte',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
